services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.58.0-noble # Version must match requirements.txt
    container_name: playwright
    command: npx -y playwright@1.58.0 run-server --port 3000 --host 0.0.0.0
    ports:
      - "3000:3000"
  
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    ports:
      - ${SEARXNG_HOST:+${SEARXNG_HOST}:}${SEARXNG_PORT:-8080}:${SEARXNG_PORT:-8080}
    env_file: ./.env
    volumes:
      - ./deployment/core-config/:/etc/searxng/:Z
      - ./deployment/core-data:/var/cache/searxng/

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - ./deployment/valkey-data:/data/

  open-terminal:
    image: ghcr.io/open-webui/open-terminal
    container_name: open-terminal
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      OPEN_TERMINAL_MULTI_USER: "true"
      OPEN_TERMINAL_API_KEY: "your-secret-key"
    volumes:
      - ./deployment/open-terminal:/home
